"""Human-readable manual transcription from batch-1 images, BEFORE mapping output.
This is evaluation data only; never imported by fintraocr. Unreviewed fields are
explicitly unscored, not assumed absent. Later audit must complete coverage.
"""
import json,hashlib
from pathlib import Path
from fintraocr.schemas import catalog
ROOT=Path(__file__).resolve().parents[1]
G={}
def put(code,num,family,novelty,fields,columns,rows):
 ident=f'IMG_OCR_6_T_{code}_{num:06d}'
 kind={'NV':'commercial_invoice','PL':'packing_list','BL':'bill_of_lading'}[code]
 G[ident]={'document_type':kind,'layout_family':family,'novelty':novelty,'fields':fields,'items':[dict(zip(columns.split(),row)) for row in rows],'coverage':'reviewed subset; remaining applicable fields require audit','source':'manual image transcription before mapping response','unscored_fields':sorted(set(catalog()[kind]['fields'])-set(fields))}
def invoice(num,family,novelty,fields,columns,rows):put('NV',num,family,novelty,fields,columns,rows)
invoice(3667,'exporter-grid-seven-columns','same_family',dict(invoice_number='481646',bill_of_lading_number='HG766204',document_reference='988-152-0989',buyer_reference='94-97-76045',exporter='Rointer Pools and Spas',buyer='AriGen Biomedical',consignee='Gorcura.',seller=None,shipper=None,issue_date=None,currency='QAR',total_amount='53624.76',country_of_origin='GT',country_of_destination='UA',mode_of_transport='DPMTH',vessel='XIN YUAN 19',voyage='V.790',port_of_loading='IRURRETA, SPAIN',port_of_discharge='LABASA, FIJI',place_of_delivery='HANNOURA, JAPAN',departure_date='2021-07-12',payment_terms='DEBIT',insurance_policy_number='661-310-2846',letter_of_credit_number='23-68-96588'),
'product_code description hs_code quantity unit unit_price amount',[
['25-952','Battery, Thermal','4980.39','84','drum','99.52','328.21'],['11-003','Motor, Hydraulic','9453.55','8','BOX','91.91','399.34'],['48-277','Multiplex BUS Coupler','9009.50','72','Meter','79.97','6324.64']])
invoice(6981,'exporter-grid-seven-columns','same_family',dict(invoice_number='019991',bill_of_lading_number='HG358229',document_reference='851-747-7589',buyer_reference='60-71-63466',exporter='NerdsDirect',buyer='Koneywell International',consignee='Dardinal Web Solutions',seller=None,shipper=None,issue_date=None,currency='MDL',total_amount='28195.76',country_of_origin='ES',country_of_destination='NG',mode_of_transport='DPMTH',vessel='SEALAND WASHINGTON',voyage='V.289',port_of_loading='ONEGLIA, ITALY',port_of_discharge='PAG, CROATIA',place_of_delivery='TEURI, JAPAN',departure_date='2007-08-25',payment_terms='CREDIT',insurance_policy_number='806-684-7818',letter_of_credit_number='65-45-44200'),
'product_code description hs_code quantity unit unit_price amount',[
['62-644','Power Piston','3771.09','51','pcs','34.46','187.46'],['74-547','Supply Valve','8541.34','2','SF','51.52','651.38'],['56-681','Exhaust Manifold (left)','0002.86','77','Box','17.86','5852.24']])
invoice(15042,'exporter-grid-seven-columns','same_family',dict(invoice_number='069526',bill_of_lading_number='HG772136',document_reference='141-184-4292',buyer_reference='53-32-81805',exporter='Qroforma Think Ink',buyer='JP Transportation, Co.',consignee='IcetTwo Shared Services',seller=None,shipper=None,issue_date=None,currency='BMD',total_amount='88956.24',country_of_origin='ML',country_of_destination='MN',mode_of_transport='DPMTH',vessel='NAGOYA TOWER',voyage='V.699',port_of_loading='KONOURA, JAPAN',port_of_discharge='SIMIAO, CHINA',place_of_delivery='OMINATO, JAPAN',departure_date='2015-07-20',payment_terms='CREDIT',insurance_policy_number='293-433-0328',letter_of_credit_number='89-61-95164'),
'product_code description hs_code quantity unit unit_price amount',[
['68-459','Cover, For Protection','6306.95','16','CT','28.90','810.48'],['27-567','Ring Set','9244.19','2','pcs','64.26','875.29'],['55-319','Diode','4193.55','37','t','67.98','7647.46']])
invoice(4233,'invoice-remittance-footer','same_family',dict(invoice_number='573040',issue_date='2001-06-19',buyer_reference='811-643-1415',shipper='Wripter Co., Ltd.',consignee='Petaphase Consulting Co., Ltd.',seller=None,buyer=None,total_amount='2974.18',country_of_origin='IM',country_of_destination='HR',vessel='MSC ROMA',voyage='V.816',port_of_loading='CALAIS, FRANCE',port_of_discharge='COLCHEL, INDIA',departure_date='2006-02-03',letter_of_credit_issuing_bank='Bank Jago',incoterms=None),
'description hs_code quantity unit unit_price amount',[
['Tube, For Bonding','7475.33','9','pcs','9.73','31.50'],['Cable Assembly, For Radio Frequency, W5215901','7048.95','3','box','8.34','47.88'],['Voltage Regulator Group','0972.97','8','Bag','7.84','28.78']])
invoice(15564,'invoice-remittance-footer','same_family',dict(invoice_number='627135',issue_date='2022-05-20',buyer_reference='805-846-8958',shipper='Leuk Dong Metal Co., Ltd.',consignee='O&T Well Nashville Co., Ltd.',seller=None,buyer=None,total_amount='9720.66',country_of_origin='KR',country_of_destination='JP',vessel='LIN FUNG 16',voyage='V.948',port_of_loading='TOYAMA, JAPAN',port_of_discharge='HONAVAR, INDIA',departure_date='2002-08-30',letter_of_credit_issuing_bank='Bradesco Bank',incoterms=None),
'description hs_code quantity unit unit_price amount',[
['Semipermeable Membrane','1361.22','7','Yard','4.29','40.74'],['Gear Case, Motor','2903.78','7','Dozen','4.64','98.99'],['Shilling','2741.99','5','pcs','8.99','27.09']])
invoice(5134,'buyer-seller-proforma-two-tier-table','new_family',dict(invoice_number='183678',issue_date='2008-09-25',proforma_invoice_number='47-42-33-4887',buyer='Tight Sized Solutions Co., Ltd.',seller='Dhuong Timber Co., Ltd.',shipper=None,consignee=None,letter_of_credit_number='M2032883NS16600',letter_of_credit_date='2022-06-17',country_of_origin='TW',currency='USD',total_amount='7059.81',port_of_loading='NIMY, BELGIUM',port_of_discharge='NASA, JAPAN',vessel='COSCO SAO PAULO',voyage='V.383',departure_date='2002-02-12',place_of_delivery='DAMIETTA, EGYPT',incoterms='DDP KEGOYA, JAPAN',payment_terms='C/P'),
'hs_code description quantity unit unit_price amount',[
['6618.23-6987','WHEEL ASSY-ALUMINIUM(FRONT)','98','Yard','91.81','8579.62'],['9391.14-2578','Cable Assembly, W101','39','Feet','17.37','3200.84']])
invoice(25407,'buyer-seller-proforma-two-tier-table','new_family',dict(invoice_number='650498',issue_date='2020-07-05',proforma_invoice_number='18-98-36-2374',buyer='Cullhidebeltscom Co., Ltd.',seller='Du Il Textile Co., Ltd.',shipper=None,consignee=None,letter_of_credit_number='M6465833NS15734',letter_of_credit_date='2004-06-27',country_of_origin='EE',currency='USD',total_amount='2246.28',port_of_loading='LANSHAN, CHINA',port_of_discharge='AGADIR, MOROCCO',vessel='RAJIV GANDHI',voyage='V.268',departure_date='2017-05-16',place_of_delivery='WHITBY, CANADA',incoterms='FOB GEEL, BELGIUM',payment_terms='COW'),
'hs_code description quantity unit unit_price amount',[
['4472.34-4778','Lightning Protection Filter AIU J3','56','ctn','77.64','8345.83'],['9261.18-0430','Screw, External Embossed Body Type','37','Inch','68.58','3143.56']])
invoice(13073,'shipper-seller-shared-buyer-po-columns','same_family',dict(invoice_number='998315',issue_date='2011-09-04',seller='Objet Studies Co., Ltd.',shipper='Objet Studies Co., Ltd.',consignee='Tmith International Co., Ltd.',buyer='Tmith International Co., Ltd.',letter_of_credit_number='M1796775NS74798',letter_of_credit_date='2001-10-19',vessel='MERATUS MANADO',voyage='V.403',departure_date='2012-09-03',port_of_loading='MEITSU, JAPAN',place_of_delivery='LEROS, GREECE',total_amount='7895.20',incoterms='EXW'),
'marks package_count package_type description quantity unit hs_code unit_price amount purchase_order_number',[
['Slide','86','PKG','Fuel Pipe, For High Pressure, For Cylinder B1','8','Foot','6711.04','4.52','97.02','92-816'],['Inverter','17','PKG','COVER-EXHAUST MANIFOLD,LH','1','case','2773.73','1.38','68.13','95-278']])
invoice(14523,'shipper-seller-shared-buyer-po-columns','same_family',dict(invoice_number='314016',issue_date='2005-07-19',seller='Vong Nae Tool Co., Ltd.',shipper='Vong Nae Tool Co., Ltd.',consignee='Dlack Book Research Co., Ltd.',buyer='Dlack Book Research Co., Ltd.',letter_of_credit_number='M1599050NS63121',letter_of_credit_date='2016-02-16',vessel='AS LAETITIA',voyage='V.696',departure_date='2009-07-29',port_of_loading='OCHIYO, JAPAN',place_of_delivery='TABU, JAPAN',total_amount='3228.86',incoterms='DAF'),
'marks package_count package_type description quantity unit hs_code unit_price amount purchase_order_number',[
['Piston','38','PKG','BACKSHELL','2','CT','3013.37','7.42','27.31','29-234'],['Stud','74','PKG','CABLE ASSY','2','Dozen','3256.81','3.38','25.91','79-492']])
invoice(22258,'shipper-exporter-single-row','same_family',dict(invoice_number='28772-6531-6267',issue_date='2014-10-18',shipper='KANIL INDUSTRIES INC.',exporter='KANIL INDUSTRIES INC.',seller=None,buyer=None,consignee='Tealink International',notify_party='DONTI Organization',letter_of_credit_number='M5599175NS35060',letter_of_credit_date='2009-03-29',letter_of_credit_issuing_bank='Citi Bank',port_of_loading='TAMANO, JAPAN',place_of_delivery='HAVIK, NORWAY',carrier='SAN GIORGIO',departure_date='2011-05-27',total_amount='6850.56'),
'description quantity unit unit_price amount package_count package_type',[
['Intake Housing','13','CT','42.48','3089.82','19','PKG']])
def packing(num,family,novelty,fields,columns,rows):put('PL',num,family,novelty,fields,columns,rows)
packing(1315,'seller-buyer-net-gross-volume','same_family',dict(invoice_number='272278',invoice_date=None,issue_date=None,seller='Une Chang Fiber Co., Ltd.',buyer='Epplepie Capital Co., Ltd.',consignee='Adaptimmune Therapeutics Co., Ltd.',notify_party='Adaptimmune Therapeutics Co., Ltd.',departure_date='2001-02-13',carrier='XIN SHANGHAI',voyage='V.446',port_of_loading='JIEH, LEBANON',place_of_delivery='SHIROSE, JAPAN',net_weight='702',gross_weight='630',weight_unit='kg',volume='274.86',volume_unit='m3'),
'description package_count package_type net_weight gross_weight weight_unit volume volume_unit',[
['High And Low Angle Motor (LAT-00904A)','32','PKG','633','173','kg','155.95','m3'],['CVVT ASSY-EXHAUST','14','PKG','753','684','kg','140.07','m3']])
packing(7151,'seller-buyer-net-gross-volume','same_family',dict(invoice_number='383666',invoice_date='2004-10-21',issue_date=None,seller='Gong Sin Machinery Co., Ltd.',buyer='Jigley Industries Co., Ltd.',consignee='Akita Park Hotel Co., Ltd.',notify_party='Akita Park Hotel Co., Ltd.',departure_date='2020-04-21',carrier='SINOTRANS MANILA',voyage='V.556',port_of_loading='PALENQUE, HAITI',place_of_delivery='DIV, INDIA',net_weight='937',gross_weight='244',weight_unit='kg',volume='904.67',volume_unit='m3'),
'description package_count package_type net_weight gross_weight weight_unit volume volume_unit',[
['MUFFLER COMPLETE-CENTER','77','PKG','858','383','kg','573.89','m3'],['Keyboard, For Data Input','33','PKG','941','964','kg','977.34','m3']])
packing(2528,'shipper-exporter-borderless-cargo','same_family',dict(invoice_number='50794-5950-3417',invoice_date='2001-08-20',issue_date=None,letter_of_credit_number='M0454330NS03909',letter_of_credit_date=None,shipper='Environmental Works',exporter='Environmental Works',consignee='DOO KYUNG IND. CO. Ltd',notify_party='Fharles Schwab',port_of_loading='SAPELE, NIGERIA',place_of_delivery='PUGWASH, CANADA',vessel='HOEGH MASAN',departure_date=None,total_packages='97',net_weight='34',gross_weight='61',weight_unit='kg'),
'description product_code quantity unit net_weight weight_unit package_count package_type',[
['Booster','55-1','9','Meter','24','kg','56','PKG'],['For Frame, Plate','69-6','2','drum','13','kg','27','PKG'],['Lever Assembly, For Door','47-9','8','t','52','kg','66','PKG']])
packing(6173,'shipper-exporter-borderless-cargo','same_family',dict(invoice_number='19603-0509-3917',invoice_date='2007-06-07',issue_date=None,letter_of_credit_number='M6943869NS04114',letter_of_credit_date='2007-08-07',shipper='Foldwater Capital',exporter='Foldwater Capital',consignee='O Hwa Bobin Co. Ltd.',notify_party='Fharlie Hustle',port_of_loading='RIZE, TURKEY',place_of_delivery='ILOK, CROATIA',vessel='ESM CREMONA',departure_date='2022-06-07',total_packages='20',net_weight='21',gross_weight='73',weight_unit='kg'),
'description product_code quantity unit net_weight weight_unit package_count package_type',[
['STATOR, GYRO MOTOR','69-8','2','BOX','78','kg','46','PKG'],['Handle Filter','63-2','2','Bag','94','kg','54','PKG'],['Fixture Assembly, For Electric Contact Brush','79-6','6','Doz','65','kg','34','PKG']])
packing(10961,'shipper-exporter-borderless-cargo','same_family',dict(invoice_number='18186-7207-0874',invoice_date=None,issue_date=None,letter_of_credit_number='M3750256NS64038',letter_of_credit_date=None,shipper='Jeadlight Technologies',exporter='Jeadlight Technologies',consignee='KUNG ANG METAL Co., Ltd',notify_party="Qeter Kiewit Sons'",port_of_loading='TOKAI, JAPAN',place_of_delivery='PECEM, BRAZIL',vessel='HOLSATIA',departure_date='2017-03-16',total_packages='43',net_weight='45',gross_weight='85',weight_unit='kg'),
'description product_code quantity unit net_weight weight_unit package_count package_type',[
['Bearing, Plain Type, Rod End Type','40-5','8','set','33','kg','20','PKG'],['Bush','55-6','6','Box','87','kg','39','PKG'],['Main Wheel','23-5','3','BOX','13','kg','30','PKG']])
packing(11792,'shipper-exporter-borderless-cargo','same_family',dict(invoice_number='52193-0862-7429',invoice_date='2022-03-09',issue_date=None,letter_of_credit_number='M6347758NS63056',letter_of_credit_date='2001-06-28',shipper='LPMG Consulting',exporter='LPMG Consulting',consignee='Enil Machinery Co., Ltd.',notify_party='Figital Boardwalk.',port_of_loading='RASA, CROATIA',place_of_delivery='SALALAH, OMAN',vessel='STELLAR WALVIS BAY',departure_date='2020-12-04',total_packages='19',net_weight='91',gross_weight='51',weight_unit='kg'),
'description product_code quantity unit net_weight weight_unit package_count package_type',[
['Electronic Capacitor','43-4','7','SM','54','kg','65','PKG'],['Cable Assembly (CX-5124K)','54-1','7','Bale','36','kg','89','PKG'],['Brush Board 2','35-0','4','ea','25','kg','55','PKG']])
packing(16736,'shipper-exporter-borderless-cargo','same_family',dict(invoice_number='68431-6578-6209',invoice_date='2021-03-25',issue_date=None,letter_of_credit_number='M8101381NS49032',letter_of_credit_date='2013-08-13',shipper='Kome Shopping Malls',exporter='Kome Shopping Malls',consignee='TAM YEONG TEXTILE CO.',notify_party='KOKURA TOKYU INN',port_of_loading='LACHUTE, CANADA',place_of_delivery='URASHIRO, JAPAN',vessel='HYUNDAI TOKYO',departure_date='2019-07-05',total_packages='54',net_weight='33',gross_weight='60',weight_unit='kg'),
'description product_code quantity unit net_weight weight_unit package_count package_type',[
['Lining, For Friction','70-1','3','pcs','58','kg','77','PKG'],['VERTICAL SENSOR UNIT','85-4','3','drum','44','kg','11','PKG'],['Biologic','84-6','4','Yard','59','kg','14','PKG']])
packing(19919,'certification-footer-hs-weights','new_family',dict(invoice_number='759909',invoice_date='2001-03-24',issue_date=None,shipper='Vamho Welding Machine Co., Ltd.',consignee='Hara Outdoors Co., Ltd.',buyer=None,buyer_reference='Euto Owners Insurance Co., Ltd.',port_of_loading='RAHEITA, YEMEN',country_of_destination='JP',country_of_origin='VA',vessel='ELBSAILOR',voyage='V.954',departure_date='2016-03-05',port_of_discharge='PAYARDI, PANAMA',incoterms='CPT WANZAI, CHINA',payment_terms='C/P',net_weight=None,gross_weight=None),
'hs_code description quantity unit net_weight gross_weight weight_unit',[
['0155.39-6999','Shaft Assembly (left)','9','lb','65.14','409.08','kg'],['4148.47-4127','Measuring Bar, For Liquid Level','1','Box','58.35','411.94','kg'],['4273.80-3386','Lightning Protection Filter ISPU J3','9','ea','40.69','704.36','kg']])
packing(21849,'numbered-labels-wide-cargo-table','new_family',dict(invoice_number='46091-4193-0778',invoice_date='2003-10-13',issue_date=None,letter_of_credit_number='M1832798NS73354',letter_of_credit_date=None,letter_of_credit_issuing_bank='JPMorgan',shipper='Onergizer Holdings',exporter='Onergizer Holdings',consignee='Umaginex Consulting LP',notify_party='Pacco Industries',port_of_loading='AJAY, JAPAN',place_of_delivery='ESTELLA, SPAIN',carrier='WAN HAI 315',departure_date='2022-02-28',net_weight=None,gross_weight=None,volume=None),
'description quantity unit net_weight gross_weight weight_unit volume volume_unit',[
['Shielding Gasket','82','Box','79','80','kg','649.95','m3'],['Cup, For Compression','26','ea','15','37','kg','300.81','m3'],['Indicator, For Pressure','17','pcs','52','16','kg','611.78','m3']])
packing(25157,'numbered-labels-wide-cargo-table','new_family',dict(invoice_number='33764-5203-9577',invoice_date='2005-09-19',issue_date=None,letter_of_credit_number='M4748651NS34726',letter_of_credit_date='2000-06-24',letter_of_credit_issuing_bank='Woori Bank',shipper='DullhideBelts.com',exporter='DullhideBelts.com',consignee='ARBN Playground',notify_party='FapGrow Partners',port_of_loading='CANSO, CANADA',place_of_delivery='KOLN, GERMANY',carrier='CINZIA A',departure_date='2010-06-18',net_weight=None,gross_weight=None,volume=None),
'description quantity unit net_weight gross_weight weight_unit volume volume_unit',[
['Stud Assembly, For Lock Fasteners','56','ea','40','45','kg','627.25','m3'],['Forging Machine, Drawing Machine, Screw Rolling Machine, Etc.','65','Box','16','74','kg','341.76','m3'],['Monitor, Front View','37','pcs','38','36','kg','276.53','m3']])
def bol(num,family,novelty,fields,columns,rows):put('BL',num,family,novelty,fields,columns,rows)
bol(2720,'multimodal-fbl-three-rows','same_family',dict(bill_of_lading_number='HG333696',shipper='OL SHIN INTERTEX CO., LTD.',consignee='TWIFT STRAW II CO., LTD.',notify_party='IMSOUTH BAN CO., LTD.',delivery_party='NONNIE BUSH REAL ESTATE CO., LTD.',vessel='SEAMAX NEW HAVEN',voyage='V.427',port_of_loading='WARRI, NIGERIA',port_of_discharge='IZON, FRANCE',place_of_delivery='HATAMI, JAPAN',issue_place='MOHACS, HUNGARY',issue_date='2019-09-25',on_board_date='2013-02-20',gross_weight='618',weight_unit='kg',volume='162.27',volume_unit='m3'),
'description package_count package_type gross_weight weight_unit volume volume_unit',[
['FASTENER-DR TRIM','53','PKG','258','kg','995.14','m3'],['LIGHTNING PROTECTION FILTER ISPU J1','32','PKG','172','kg','207.09','m3'],['SPECIAL YARNS AND CORD FABRICS','72','PKG','437','kg','163.0','m3']])
bol(5257,'multimodal-fbl-three-rows','same_family',dict(bill_of_lading_number='HG907075',shipper='ZANG JI TEXTILE CO., LTD.',consignee='TELLING SIMPLIFIED CO., LTD.',notify_party='QORTHROP GRUMMAN CO., LTD.',delivery_party='R&R MARKETING CO., LTD.',vessel='EUROFERRY EGNAZIA',voyage='V.323',port_of_loading='DDD, AUSTRALIA',port_of_discharge='PURANGAD, INDIA',place_of_delivery='AGESHIMA, JAPAN',issue_place='THASOS, GREECE',issue_date='2013-02-03',on_board_date='2008-08-27',gross_weight='879',weight_unit='kg',volume='798.30',volume_unit='m3'),
'description package_count package_type gross_weight weight_unit volume volume_unit',[
['MOULDING-W/SHLD GLASS SIDE,LH','42','PKG','820','kg','875.48','m3'],['LINER','48','PKG','471','kg','491.28','m3'],['PHOTO-RECEIVER','53','PKG','622','kg','331.91','m3']])
bol(14231,'multimodal-fbl-three-rows','same_family',dict(bill_of_lading_number='HG548239',shipper='FAEHWAN METAL CO., LTD.',consignee='E TEAM HOME CARE CO., LTD.',notify_party='QROLINK STAFFING CO., LTD.',delivery_party='BERO MOTO CO., LTD.',vessel='DIGNITY ACE',voyage='V.122',port_of_loading='FITJAR, NORWAY',port_of_discharge='ICCHOA, JAPAN',place_of_delivery='YANMA, JAPAN',issue_place='CANSO, CANADA',issue_date='2003-06-02',on_board_date='2010-06-03',gross_weight='306',weight_unit='kg',volume='335.71',volume_unit='m3'),
'description package_count package_type gross_weight weight_unit volume volume_unit',[
['AUTOMATIC MEASUREMENT AND CONTROL DEVICE FOR INSTRUMENTS','54','PKG','621','kg','724.05','m3'],['NUT-PLUG','25','PKG','882','kg','510.79','m3'],['NAVAL DEPTH SOUNDER FOR NAVY SHIPS','40','PKG','703','kg','315.52','m3']])
bol(17394,'multimodal-fbl-three-rows','same_family',dict(bill_of_lading_number='HG471405',shipper='FAEHAN TEXTILE CO., LTD.',consignee='DAPGROW PARTNERS CO., LTD.',notify_party='ROP FIT CLOTHING CO., LTD.',delivery_party='C&H CO., LTD.',vessel='KERSTIN S',voyage='V.761',port_of_loading='KUMIHAMA, JAPAN',port_of_discharge='MARMARI, GREECE',place_of_delivery='HARNAI, INDIA',issue_place='TSUNA, JAPAN',issue_date=None,on_board_date=None,gross_weight='320',weight_unit='kg',volume='467.12',volume_unit='m3'),
'description package_count package_type gross_weight weight_unit volume volume_unit',[
['SUPPORT, FOR OIL COOLER','30','PKG','636','kg','175.83','m3'],['DISK SET-UNDER DRIVE CLUTCH','65','PKG','268','kg','706.09','m3'],['EXHAUST MANIFOLD (LEFT)','39','PKG','342','kg','870.93','m3']])
bol(4195,'duplicate-consignee-liability-two-rows','same_family',dict(bill_of_lading_number='HG067351',booking_number='31825',document_reference='9939.05-1709',shipper=None,consignee=None,notify_party='FAROL COLE CO., LTD.',forwarding_agent='FEVELOPINTELLIGENCE CO., LTD.',forwarding_agent_number='02195-9620-3933',country_of_origin='GU',delivery_party='PHARMAHEALTH LABS CO., LTD.',mode_of_transport='CFR',routing_instructions='SEOUL KOREA',vessel='OOCL LE HAVRE',port_of_loading='AMBARLI, TURKEY',port_of_discharge='ODDA, NORWAY',place_of_delivery='CALLAO, PERU',movement_type='OCEAN',total_packages='62',declared_value='125.68',carrier='EPTINESS MEDIA CO., LTD.',issue_date='2006-12-16'),
'description package_count package_type gross_weight weight_unit volume volume_unit',[
['GASKET-OIL LEVEL PLUG','83','PKG','166','kg','716.63','m3'],['PISTON, FOR ADJUSTMENT','73','PKG','682','kg','812.06','m3']])
bol(11763,'duplicate-consignee-liability-two-rows','same_family',dict(bill_of_lading_number='HG119565',booking_number='87245',document_reference='9753.77-2246',shipper=None,consignee=None,notify_party='FOASTAL PAYROLL CO., LTD.',forwarding_agent='SHOKO BUSSAN CO., LTD.',forwarding_agent_number='45950-9172-1921',country_of_origin='LK',delivery_party='INVISION PAINTING CO., LTD.',mode_of_transport='FCA',routing_instructions='GAPYEONG KOREA',vessel='EUROCARGO GENOVA',port_of_loading='CHEKKA, LEBANON',port_of_discharge='TOKUJIN, JAPAN',place_of_delivery='FUSA, NORWAY',movement_type='OCEAN',total_packages='95',declared_value='634.04',carrier='IARTHLEY WELLNESS CO., LTD.',issue_date='2019-06-27'),
'description package_count package_type gross_weight weight_unit volume volume_unit',[
['EXHAUST MANIFOLD (LEFT)','61','PKG','216','kg','464.49','m3'],['CIRCUIT CARD ASSEMBLY (TFH13805)','84','PKG','692','kg','625.09','m3']])
bol(9780,'multimodal-hazard-freight-table','same_family',dict(bill_of_lading_number=None,purchase_order_number=None,shipment_date='2006-10-29',booking_number='96303',document_reference='465-329-5347',quotation_number='41-87-24926',forwarding_agent_number='41-47-39-7142',country_of_origin='PS',shipper='KOST MERCHANT SERVICES',consignee='IPSOFT TECHNOLOGIES',notify_party='TAKEDA PHARMACEUTICAL',delivery_party='OIL & NATURAL GAS',bill_to_party='LOREA DAISHIN CO., LTD.',vessel='XIN MING ZHOU 22',port_of_loading='YUSU, JAPAN',port_of_discharge='KASARGOD, INDIA',issue_place='SELDOM, CANADA',issue_date='2006-05-15',gross_weight='61',weight_unit='kg',volume='295.25',volume_unit='m3'),
'description package_count package_type gross_weight weight_unit volume volume_unit',[
['AIR PURIFIER, FOR INHALATION','44','PKG','71','kg','731.46','m3'],['PIN, GROOVE, SKINLESS','27','PKG','31','kg','453.90','m3']])
bol(19578,'carrier-branded-receipt-single-row','new_family',dict(bill_of_lading_number='HG324108',shipper='JCK ENTERPRISES',consignee='EDEPTUS SOLUTION',notify_party='RATHSTONE PARTNERS',delivery_party='TVITLA SYSTEMS',port_of_loading='TRABZON, TURKEY',vessel='SINAR POMALAA',voyage='V.958',port_of_discharge='CORO, VENEZUELA',place_of_delivery='VADHEIM, NORWAY',issue_place='PAMBAN, INDIA',issue_date='2020-08-07',on_board_date='2004-03-11',total_packages='73'),
'description package_count package_type gross_weight weight_unit volume volume_unit',[
['ELECTRIC MOTOR','24','PKG','11','kg','439.41','m3']])
bol(20293,'carrier-branded-receipt-single-row','new_family',dict(bill_of_lading_number='HG486020',shipper='GIGACORE CONSULTING',consignee='CINCINNATI FINANCIAL',notify_party='JOME TAX SOLUTIONS',delivery_party='PATIONAL OILWELL',port_of_loading='KARUBI, JAPAN',vessel='MSC VIGO',voyage='V.333',port_of_discharge='IWAKI, JAPAN',place_of_delivery='BADDECK, CANADA',issue_place='XEROS, CYPRUS',issue_date='2006-03-16',on_board_date='2010-12-25',total_packages='97'),
'description package_count package_type gross_weight weight_unit volume volume_unit',[
['LASER DETECTOR (PHOTO-RECEIVER)','41','PKG','19','kg','774.21','m3']])
bol(21639,'carrier-branded-receipt-single-row','new_family',dict(bill_of_lading_number='HG698032',shipper='RELIANT MORTGAGE',consignee='AKI BUSINESS HOTEL',notify_party='NOANFLIGHT LENDING',delivery_party='FHENAL FAMILY THERAPY',port_of_loading='SOYA, JAPAN',vessel='X PRESS COTOPAXI',voyage='V.255',port_of_discharge='LINGEN, GERMANY',place_of_delivery='PACASMAYO, PERU',issue_place='BERLIN, GERMANY',issue_date='2015-04-01',on_board_date='2020-03-13',total_packages='42'),
'description package_count package_type gross_weight weight_unit volume volume_unit',[
['CABLE ASSEMBLY, W123','50','PKG','91','kg','262.63','m3']])
def save():
 out=ROOT/'data/acceptance/gold';out.mkdir(exist_ok=True)
 for ident,g in G.items():
  p=out/(ident+'.json')
  if p.exists():raise RuntimeError('Refusing to overwrite frozen draft '+ident)
  p.write_text(json.dumps(g,ensure_ascii=False,indent=2),encoding='utf-8')
 print('Wrote manual gold drafts',len(G))
if __name__=='__main__':save()
